hash-format = "sha256"

[[files]]
file = "mods/adorabuild-structures.pw.toml"
hash = "82d1bae0fb3724315ef3829aacb25ddc273ccc9c6b965bdf20343387dfba1a5f"
metafile = true

[[files]]
file = "mods/animationoverhaul.pw.toml"
hash = "398ca3e146b3be50656f80542d6b9dd95b9becb065624e6dcc49d798712c5f99"
metafile = true

[[files]]
file = "mods/another-furniture.pw.toml"
hash = "1ba6c0a621ef7ca001fe2a7c7c2322f1f7a4b2c93f3a5adc3b548097f8d366de"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/ati-structures-vanilla-edition.pw.toml"
hash = "999fad53e62ac2a4d4f799f342d8b843522c0f4d2710edcc0c3d82b5d19cefe1"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
hash = "b6060e92c302e4db7c1040a1e6f2d9f59998d1e18e10e0c8734c7659eb003c01"
metafile = true

[[files]]
file = "mods/autoshutdown.pw.toml"
hash = "3bb481516286924d6a72fbc8038452db198c314cf7d65c3b2784fd7150c86d5b"
metafile = true

[[files]]
file = "mods/beautify-refabricated.pw.toml"
hash = "724353a7730f54b29378ba8e374c78372c8a8f072e578b5758b11fc150f470b7"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "bee459c3b3739a46717f04675ba175d8a5d26fc00a8683acd4ef5bdfb73a9066"
metafile = true

[[files]]
file = "mods/better-village.pw.toml"
hash = "caec4dd39cda8f695c2d7c9923cf5375fa2360f95ce4d34c9cdf99b626e5d99b"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "a2de85ebe9629568398185b5b9554bcc0c54e322b214d78368485a6074a66279"
metafile = true

[[files]]
file = "mods/blahaj.pw.toml"
hash = "6447d9f9933ee9085520af83a0d85d2a46e2e8691173df443feebdcb0d893aba"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "2f57caef93731338be19b1e14065978eb3e14dbfc0c1f9699dfcc2f201e2c23b"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "0ed502ad7d53ca1936079cb7508b2e085909610ac51337fff2a3ce0fa6dcae28"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "b4fdf52d53ab71bf73282c5168e9526b6024740d82388d604d6947394e3c7f7f"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "f460d01d0351226ce596672936cc09364028046e87fc357bd0218c6df3e89d83"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "3681a4dd6134dc64b5af240379c1f98023b2217fd6af8c08763d3228bad01fbe"
metafile = true

[[files]]
file = "mods/create-diesel-generators-fabric.pw.toml"
hash = "ee3138fd5b546f541d90a01c2deb0ec00abec4ca54b3195d46e6a32bd12a50a3"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "7d227ef90b1918ceb348ade235a5d17c7894acbf387575e96c08920a5bad1bbb"
metafile = true

[[files]]
file = "mods/create-food.pw.toml"
hash = "8d5b5be2a11185472ef0f4ad317c94fe91a7c7bdf04e0d06dee542a7c09e2eed"
metafile = true

[[files]]
file = "mods/create-let-the-adventure-begin.pw.toml"
hash = "acaceb356e4d6ebd3a904dacabe927e1cac94799f12b212e01c5e0dc22b09e66"
metafile = true

[[files]]
file = "mods/create-ore-excavation.pw.toml"
hash = "62ee505db03ae305933198e59250095ca5403b65abf02fbee6d5216e02d5c10e"
metafile = true

[[files]]
file = "mods/create-pantographs-and-wires.pw.toml"
hash = "5d45a62f15b6bd6b3aa37fd3250103849025e0281aaa56010d9283ddde3299d6"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "b79bc9976d5958f4b88ca23575e0d0dc677a2b06931108f6f7bc3fd3e46bb22c"
metafile = true

[[files]]
file = "mods/create-trainutilities.pw.toml"
hash = "f9784ac1511b83e0e3bf7df5b2240170d41e01b285b2b4455ef702113451aa6a"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "c9a378fded69f10157712ea481e8a97fe6cd91e72c761971aeea45dadc330389"
metafile = true

[[files]]
file = "mods/createnuclear.pw.toml"
hash = "a583a5e1190ef2189487ee5bd87d0adebbc8fcbb31d828a48d28a5104f9c1e06"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "6ec7fc70c84dc7f7f4578a85480264d82336d64ac0d8c95c0fcc55d350f64ab7"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "b8973dec5c378727ef26cec7b775722fedaeaaa36b98912eed1c5898196e6e9e"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "0bcc0df994ebbe98efc2f87c653cd0ae0a81bb0ca47b5adacba0974c5c6406c5"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "71644e8041262193332f28d24b649c06c81074a983c6e3acd18b62a117b68b60"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "e9ba6ffa1109ca957fef061ef4b41a46300b3cfb382ef4ae24f96c54309fd31f"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "fec1ffa03b4d62e47be25512840490844fc383cf82d2ad35345b2f87a21e8228"
metafile = true

[[files]]
file = "mods/enchanting-infuser.pw.toml"
hash = "7a3a066a9e6da4873a54bdad10e6749be5d32026decbc83bd4ebe59f60b9f97f"
metafile = true

[[files]]
file = "mods/enhanced-cats.pw.toml"
hash = "a58910e720857984ccd736ee9e2899e784029f5a40c02b278d33c3f6752706d4"
metafile = true

[[files]]
file = "mods/estrogen.pw.toml"
hash = "14272998f333bd1cc6d2b8a3d9f2d5430693f065f74d8cec680b94a5facabb7c"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
hash = "91dab84ae147fd26d1b61456329b78e76ef4109c21ecf9f96b6f967618079ab7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "e09385ac1a1c0900b8fa619290eb0f0539949ebbc59f7604a7699485784ccc85"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "adea09f1e1b05da68cf7407992a9391b15985acf5465a888e54ae076dbd543ab"
metafile = true

[[files]]
file = "mods/formations-overworld.pw.toml"
hash = "a9ed985d2453f61db49f2af28c30d40119a0654f9a58dc850f24eaad50417150"
metafile = true

[[files]]
file = "mods/formations.pw.toml"
hash = "dfe0fb2bcdb8a356dae8f654710b72ea9c532c7b05afee33186de068df492ffb"
metafile = true

[[files]]
file = "mods/friends-and-foes-beekeeper-hut-fabric.pw.toml"
hash = "be27c9f5c78d11f671f3d5673bbd8fafb45c615ee542fe5d8a8f4f44c6bdaadd"
metafile = true

[[files]]
file = "mods/friends-and-foes-flowery-mooblooms-fabric.pw.toml"
hash = "20c0294134def2e3d0bf739e7c5b6860ed374d1658017df47bd3ff1eb1b7176e"
metafile = true

[[files]]
file = "mods/friends-and-foes.pw.toml"
hash = "2fcd17a965738c1649d434a0d5f8077321b4bb90a8c9d9d868d220d8bbd5abb3"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "21d2df923fa369d69a40d69f6466153146bf403367430eaeb2569c1554857df8"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
hash = "17a39f71985dd963c15fe6ed5acf7cff675c7d5d0a8508a2664767c911faea51"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "493ed95320ee3cc9c2def86b9d0971c2ca4bb4215921c2a11208bee77d5dbfb5"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "ca3ca3f51541688c45a81c541ff46660853106ebda282dfd59da00f5c9c0a9cd"
metafile = true

[[files]]
file = "mods/immersive-melodies.pw.toml"
hash = "40a8d97db3162ea083e5ad40a6a8f7ba0f260d714b74854ba77d2644e1914bbf"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "96b6a9192639045bc5b2c0815ad33d1d754bf77e2f59bd96dd3bde21784d7704"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "cc5ce2c69f275f245fccbb9f673f5b6711175034bdf41f48cfb672e652ea984b"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
hash = "fd806713c4bd32080e12e65c012ad93de6a6fae53484fa13a72603c39f3eae63"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "a51d746fdd98949eb47b83a9da95a1121fd7163601e901d986e57b1d2aca7950"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "211d05efd962f20f4eb4704ae6f781960f7931abb687e14b42fead9c980e7a95"
metafile = true

[[files]]
file = "mods/journeymap-integration.pw.toml"
hash = "a4cedb3070c2c911e92674a78c9645b7e7ca79bca991a6243536cace8b99dd1a"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "c1cc1e05c95d769dd4929825e6a85d5ac8023d4a018569f40dd7bd972a81655e"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8508e46b7e272d79dc6b3cc0149f9fd132c701369bcb2abb5c35da3ed92b27fb"
metafile = true

[[files]]
file = "mods/leashable-collars.pw.toml"
hash = "1f07d2b172b4f14ed7cb8c7e9dacb6e140a0b2fd830c00393a72a69ed8627603"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "cc298019c2d3a47a97e72363b942fe408e5ecb7ff476fe08155793f2f1578317"
metafile = true

[[files]]
file = "mods/library-ferret.pw.toml"
hash = "be4bb351c89fb18c5166578ef42006e32138bdb1e356ba7db0723ad49c4272c4"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c8695e51366b601c5e9118a5d5650d234cc25fc8d1f90ebd186c17c199ba7fca"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "55167e582fd4841cd6c581beb53d341e94285c216e04b1d7bff0068e875be2a6"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "0d438cc5a467aae6a9aa439a4547f990dfbaa4dc4e7bf5dbabf6d6e839411e83"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/moogs-structure-lib.pw.toml"
hash = "8b64ba3552679ed5a622fbffb8875d6b6a185f39ca4966fed28197a4b031b6e3"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
hash = "c309f7b7186fb246c6e72db4b8aef81a77e3ee793978aaf2e34318ce4dfcf014"
metafile = true

[[files]]
file = "mods/naturalist.pw.toml"
hash = "2149e8ba3fc2c56905e6bbc06efd4ece5999d8babea605386ec5bd1af26aef90"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "38aa99dcb8b2371b04716226723ab30b8954fcc80a503d20c12fc7fc519f26e9"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "9cd1bfa718de9a9707fbd76216e5a0c06b00d5fb393ecc55e43b9c6c578a4817"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "3c2fe6485d980a094a5094263d9d54dd59bd4cfd37439109be561894342a82f8"
metafile = true

[[files]]
file = "mods/pride-moths.pw.toml"
hash = "ab0ef96f83ac6d59519db6beab67ec94f23a2e3a9cd50c0f4361a0ef135e3481"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "a1eff7b33a54586b6989c7bfd89992f9d315f1c656b7596649d9af7017c6af7b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "4a7d1e46795d2d83b18db85d8dbc63740a1d337e12d2b9e550378de59f2b23ab"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.pw.toml"
hash = "63273748b9bbadcfefedc5bc5fddfe367d637abd094c1f931b7ab9e720dd58b2"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "77a658a9d9cec5037136b95c42d1dff26dbf4010f17ecb2116bebf69178a03ba"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "3f9e020fb15e1c2ede36d50b40c72d536f6de3f817bd703d26805a747175c8bc"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "a900fde25ea70ce75001d28cb2bdec27b6ff49fd3edee938ff7994fe84843497"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "d806cab693925db51ec429bd5aaaf7d7872793be835b346066b76941c08bcb13"
metafile = true

[[files]]
file = "mods/simple-hud-enhanced.pw.toml"
hash = "7b2026357228fe41eeb3b4e0afbf39a7465a26a0f152bbea95d23ef55a383a5c"
metafile = true

[[files]]
file = "mods/small-cat-statues.pw.toml"
hash = "9e783fdc88f85c65b2854444f28ecc26ba1f43246916e407fafc11805f22ceec"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8ad07191dfdea31249b4416a390c1cdf1d4ff1938cf9f8a617f98f7a08c5356c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "98553c2d49ef3a888954f24b7c49fe3442c01fd4fc1f1ed52c5898ed29d29d3b"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "b3ae602303fd717bff2344bfb89aa427e2b4a1ab5fffdcc25183b22102c492df"
metafile = true

[[files]]
file = "mods/the-lost-castle.pw.toml"
hash = "8cd62328b33b5d35d5659bc20a2d92357254af6950eb63fbb55d68a1f2b2a8b2"
metafile = true

[[files]]
file = "mods/tidal-towns.pw.toml"
hash = "9afc7aa9f96e76f806891d8ee5d6be77d06a370328323462f689541d0e9c8b02"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "7b7108d879e1e1c141b24d0d8fa268a6bbcd5c227875d156fcc62c3beec55f63"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "784c9a130f2eb92134e456aee15cf2c5f273af0848640fdddf33d4a7ecad8cbe"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "ffdb79f5bc29f990e5889f5d159a043c7046b8cd8d79f17f54b44d7ccc2b242a"
metafile = true

[[files]]
file = "mods/universal-bone-meal.pw.toml"
hash = "3bfed0a852a79f001106405e9964c96eb552ffd4ff247698fbe1d49e76838db6"
metafile = true

[[files]]
file = "mods/villages-and-pillages.pw.toml"
hash = "72f2140e2ecb08dca86808eeb38caf84a5650b5d7bbe54cd7f261cc91dfb8830"
metafile = true

[[files]]
file = "mods/yigd.pw.toml"
hash = "fc1d7a1ee1bb2d4906b2686d105c82b67297e8a8376bd3882fea0fdb7e6499eb"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "95940b5fc72e8df82ab3adb72b43d10a37e6d926fbb37c405c9fe50bda27a991"
metafile = true

[[files]]
file = "mods/yungs-better-caves.pw.toml"
hash = "51e404ac23d0613de9b5095e8ac6492d06eb906ec81ed86228f75b11b851838f"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "7dd536d000999274472fa6762bcd49deaeb301fd0889c32723c1129db2400561"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "0958d9f10d0e8fb282b8e684b05b37b29aca826d48deeec3e44171857c99aca5"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "c360a4aef0ce719d385529002ba157a731d572b73cefb573c763d71d54039078"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "a837a0028b1e1bbb6c4e5d31bf3cb04d6f6dccae90fc93df46f9a60a8b2c53c1"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "cf708ff146f867df2153b3f27482e80769c7032b10037e4a752d31fbb5668eaf"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "8bc20a4cf22bdd4406a64126647cfe3c704e80a3197031c9154032905a276705"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "f23d28e95b21a9655e615390a560bc66f3cb87610ac38cd9d849129d0600a766"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "b2af03e504a1827f2f6fc09597e7d51f4ecd64ab1ebb329a9eb9ffb98372673a"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "0b5eb310353cce6e94ffb0558cb713815b63328e6e96f804f147b5291c237a98"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "7e89ac9ea56f87a811a289d474b8ab4fe46d7a235b4c6ef4767e5099967d656e"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "d201155cab7c2a2cf940d91f240be769ac12046c2fc6a0774e225a8e51423ed0"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/makeup-ultra-fast-shaders.pw.toml"
hash = "05dd4aac0131eeef4c1ff5601c294e615cbc38890e50dda7ecbd18c14d2748eb"
metafile = true

[[files]]
file = "shaderpacks/rethinking-voxels.pw.toml"
hash = "6eab1c7b54fe8538afd2e260f44ea46316ad6edf8132f5699deb2b1a4584ebd7"
metafile = true
