name = "JimmyBrown"
author = "Femboys"
version = "25.2590.1563578"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1408648030b298baadfc04de7ba29f77101097f2c34ebb7941f0070cbdfb661"

[versions]
fabric = "0.18.3"
minecraft = "1.20.1"
