name = "JimmyBrown"
author = "Femboys"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d281f06f4b00673cc38ecf7a1b4f915804dce3cf1b90a5cdbc71115721a7fb13"

[versions]
fabric = "0.18.3"
minecraft = "1.20.1"
