name = "JimmyBrown"
author = "Femboys"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39303182b84cce0721a14fb47824c572aaf21d711836a76ea2b6ca099ef1509a"

[versions]
fabric = "0.18.3"
minecraft = "1.20.1"
