name = "JimmyBrown"
author = "Femboys"
version = "1.7.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8c4fe8c83c99e0f9df9862ffc78608b329f3e4c9d7cba965a33d39e06a04e07"

[versions]
fabric = "0.18.3"
minecraft = "1.20.1"
