name = "JimmyBrown"
author = "Femboys"
version = "25.2590.1563578"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c2d81034c28ea9c702b2bfd7dee40cf70d6a8bb8abb55c524e2a04dd02312a3"

[versions]
fabric = "0.18.3"
minecraft = "1.20.1"
