name = "JimmyBrown"
author = "Femboys"
version = "25.2590.1563578"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8b0ae61c2582b6e52c24c87ce489dfae1066406ff8569e7bd85be87ee5fec0c"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
